In [1]:
import pandas as pd
import numpy as np
import datetime
from datetime import datetime
from datetime import date

In [2]:
fp = 'monthly_data.dat'
openET = pd.read_csv(fp, sep = '\t', header = 1)
openET

,Site ID,geeSEBAL,PT-JPL,SSEBop,SIMS,eeMETRIC,DisALEXI,Ensemble,DATE
0,US-Blk,16.2,12.1,20.7,NaN,9.2,12.5,14.2,2004-02-01
1,US-Blk,6.2,3.7,35.7,NaN,10.9,13.1,8.5,2004-12-01
2,US-Blk,10.0,6.2,19.0,NaN,4.9,15.8,11.2,2005-01-01
3,US-Blk,11.8,15.1,26.8,NaN,9.5,26.4,17.9,2005-02-01
4,US-Blk,40.0,29.5,41.5,NaN,22.0,55.2,37.7,2005-03-01
...,...,...,...,...,...,...,...,...,...
4095,VR,159.2,165.3,200.3,NaN,201.9,186.7,182.7,2003-07-01
4096,VR,163.8,165.0,181.5,NaN,188.4,158.4,167.2,2003-08-01
4097,VR,111.4,136.1,154.9,NaN,110.8,115.8,118.5,2003-09-01
4098,VR,22.4,61.0,24.6,NaN,11.2,29.9,22.0,2003-12-01
4099,VR,192.3,174.5,202.3,NaN,203.7,193.0,193.2,2004-05-01

In [3]:
site_id = openET["Site ID"].values
dates = openET["DATE"].values
openET_sites = openET['Site ID'].unique()

In [4]:
site_time = np.ndarray(shape = (len(openET_sites),5), dtype = 'O')
site_time[:,0] = openET_sites


for i in range(len(openET)-1):
  for j in range(len(openET_sites)):
    if site_id[i] == openET_sites[j] and site_id[i-1] != openET_sites[j]:
      site_time[j,1] = dates[i]
    if site_id[i] == openET_sites[j] and site_id[i+1] != openET_sites[j]:
      site_time[j,2] = dates[i]
    difference = np.datetime64(site_time[j,2]) - np.datetime64(site_time[j,1])
    site_time[j,3] = (difference.astype('timedelta64[Y]').item())
    site_time[124,2] = '2004-05-01'
site_time

array([['US-Blk', '2004-02-01', '2008-03-01', 4, None],
       ['US-Blo', '2004-03-01', '2007-09-01', 3, None],
       ['US-CZ3', '2009-07-01', '2012-06-01', 2, None],
       ['US-Fmf', '2005-09-01', '2010-11-01', 5, None],
       ['US-Fuf', '2005-10-01', '2010-11-01', 5, None],
       ['US-GLE', '2001-06-01', '2017-11-01', 16, None],
       ['US-Me2', '2002-03-01', '2020-06-01', 18, None],
       ['US-Me5', '2001-02-01', '2002-12-01', 1, None],
       ['US-Me6', '2011-06-01', '2020-06-01', 9, None],
       ['US-NC2', '2017-04-01', '2019-06-01', 2, None],
       ['US-NC3', '2017-02-01', '2018-03-01', 1, None],
       ['US-NR1', '2001-02-01', '2019-12-01', 18, None],
       ['US-SP2', '2001-02-01', '2003-12-01', 2, None],
       ['US-SP3', '2001-02-01', '2008-11-01', 7, None],
       ['ALARC2_Smith6', '2018-02-01', '2018-05-01', 0, None],
       ['Almond_High', '2016-11-01', '2019-09-01', 2, None],
       ['Almond_Low', '2016-10-01', '2019-09-01', 2, None],
       ['Almond_Med', '2016-10-01', '2019-09-01', 2, None],
       ['BAR012', '2017-06-01', '2020-10-01', 3, None],
       ['B_01', '2005-04-01', '2007-03-01', 1, None],
       ['B_11', '2005-04-01', '2006-12-01', 1, None],
       ['Ellendale', '2018-10-01', '2020-05-01', 1, None],
       ['ET_8', '2003-09-01', '2004-10-01', 1, None],
       ['LYS_NE', '2013-06-01', '2016-09-01', 3, None],
       ['LYS_NW', '2013-07-01', '2016-09-01', 3, None],
       ['LYS_SE', '2013-06-01', '2016-09-01', 3, None],
       ['LYS_SW', '2013-07-01', '2016-09-01', 3, None],
       ['manilacotton', '2016-06-01', '2018-08-01', 2, None],
       ['MB_Pch', '2012-04-01', '2014-10-01', 2, None],
       ['RIP760', '2017-06-01', '2020-09-01', 3, None],
       ['S2', '2017-10-01', '2020-10-01', 3, None],
       ['SLM001', '2013-07-01', '2020-10-01', 7, None],
       ['UA1_HartFarm', '2019-01-01', '2019-04-01', 0, None],
       ['UA1_JV187', '2018-04-01', '2018-06-01', 0, None],
       ['UA1_KN18', '2018-10-01', '2018-11-01', 0, None],
       ['UA2_JV330', '2019-01-01', '2019-01-01', 0, None],
       ['UA3_JV108', '2018-04-01', '2018-05-01', 0, None],
       ['US-AR1', '2009-06-01', '2012-12-01', 3, None],
       ['US-ARM', '2003-01-01', '2020-08-01', 17, None],
       ['US-Bi1', '2016-09-01', '2019-12-01', 3, None],
       ['US-Bi2', '2017-05-01', '2020-06-01', 3, None],
       ['US-Bkg', '2005-03-01', '2009-02-01', 3, None],
       ['US-Bo1', '2001-03-01', '2007-08-01', 6, None],
       ['US-Br1', '2005-05-01', '2011-10-01', 6, None],
       ['US-Br3', '2005-03-01', '2011-10-01', 6, None],
       ['US-Dk1', '2006-02-01', '2008-07-01', 2, None],
       ['JPL1_Smith5', '2018-01-01', '2018-03-01', 0, None],
       ['US-Mj1', '2013-06-01', '2013-08-01', 0, None],
       ['US-Tw2', '2012-06-01', '2012-08-01', 0, None],
       ['US-KLS', '2012-06-01', '2017-12-01', 5, None],
       ['US-Mj2', '2014-06-01', '2014-08-01', 0, None],
       ['US-Ne1', '2001-07-01', '2019-12-01', 18, None],
       ['US-Ne2', '2001-07-01', '2019-12-01', 18, None],
       ['US-Ne3', '2001-07-01', '2019-12-01', 18, None],
       ['US-OF1', '2017-06-01', '2017-08-01', 0, None],
       ['US-OF2', '2017-07-01', '2017-07-01', 0, None],
       ['US-OF4', '2018-07-01', '2018-07-01', 0, None],
       ['US-OF6', '2018-06-01', '2018-07-01', 0, None],
       ['US-Ro1', '2011-03-01', '2016-12-01', 5, None],
       ['US-Ro2', '2016-02-01', '2016-11-01', 0, None],
       ['US-Ro3', '2005-03-01', '2006-05-01', 1, None],
       ['US-Ro5', '2017-02-01', '2017-12-01', 0, None],
       ['US-Ro6', '2017-02-01', '2017-12-01', 0, None],
       ['US-Tw3', '2013-06-01', '2018-05-01', 4, None],
       ['US-Twt', '2009-04-01', '2017-03-01', 7, None],
       ['AFS', '2011-12-01', '2013-10-01', 1, None],
       ['BPHV', '2012-10-01', '2013-09-01', 0, None],
       ['BPLV', '2012-10-01', '2013-08-01', 0, None],
       ['KV_4', '2011-11-01', '2012-10-01', 0, None],
       ['SPV_3', '2005-09-01', '2007-08-01', 1, None],
       ['US-ARb', '2005-04-01', '2006-05-01', 1, None],
       ['US-ARc', '2005-06-01', '2006-01-01', 0, None],
       ['US-Ctn', '2007-04-01', '2009-08-01', 2, None],
       ['US-FPe', '2001-10-01', '2008-04-01', 6, None],
       ['US-Aud', '2003-02-01', '2011-06-01', 8, None],
       ['US-Fwf', '2005-09-01', '2010-12-01', 5, None],
       ['US-Goo', '2002-07-01', '2006-09-01', 4, None],
       ['US-LS1', '2003-04-01', '2007-05-01', 4, None],
       ['US-SCg', '2006-08-01', '2016-09-01', 10, None],
       ['US-SdH', '2005-03-01', '2009-09-01', 4, None],
       ['US-SRG', '2008-06-01', '2020-05-01', 11, None],
       ['US-Var', '2003-11-01', '2020-07-01', 16, None],
       ['US-Wkg', '2004-06-01', '2020-05-01', 15, None],
       ['US-Dix', '2007-02-01', '2008-03-01', 1, None],
       ['US-Dk2', '2006-02-01', '2008-10-01', 2, None],
       ['US-FR2', '2005-05-01', '2008-11-01', 3, None],
       ['US-GMF', '2001-03-01', '2001-12-01', 0, None],
       ['US-MMS', '2004-04-01', '2020-06-01', 16, None],
       ['US-MOz', '2011-06-01', '2017-12-01', 6, None],
       ['US-Slt', '2009-09-01', '2012-11-01', 3, None],
       ['US-SRC', '2008-05-01', '2014-04-01', 5, None],
       ['US-WBW', '2001-06-01', '2005-10-01', 4, None],
       ['US-WCr', '2006-06-01', '2019-06-01', 12, None],
       ['AFD', '2011-12-01', '2013-10-01', 1, None],
       ['DVDV', '2009-10-01', '2011-09-01', 1, None],
       ['ET_1', '2004-01-01', '2004-09-01', 0, None],
       ['KV_1', '2011-09-01', '2012-07-01', 0, None],
       ['KV_2', '2010-09-01', '2012-08-01', 1, None],
       ['SPV_1', '2005-11-01', '2007-07-01', 1, None],
       ['SV_6', '2007-10-01', '2009-04-01', 1, None],
       ['UMVW', '2006-01-01', '2006-09-01', 0, None],
       ['US-ADR', '2011-06-01', '2017-04-01', 5, None],
       ['US-Ced', '2007-05-01', '2014-10-01', 7, None],
       ['SV_5', '2007-10-01', '2009-09-01', 1, None],
       ['US-Jo2', '2010-09-01', '2019-09-01', 8, None],
       ['US-KS2', '2001-02-01', '2006-11-01', 5, None],
       ['US-Rwf', '2014-07-01', '2018-09-01', 4, None],
       ['US-Rws', '2014-10-01', '2018-09-01', 3, None],
       ['US-SCs', '2006-08-01', '2016-09-01', 10, None],
       ['US-SCw', '2006-06-01', '2016-05-01', 9, None],
       ['US-SO2', '2004-06-01', '2006-10-01', 2, None],
       ['US-SO3', '2004-06-01', '2004-09-01', 0, None],
       ['US-SO4', '2005-04-01', '2006-08-01', 1, None],
       ['US-SRM', '2004-02-01', '2020-05-01', 16, None],
       ['US-SRS', '2011-06-01', '2018-06-01', 7, None],
       ['WRV_1', '2005-09-01', '2007-07-01', 1, None],
       ['WRV_2', '2006-09-01', '2007-08-01', 0, None],
       ['MR', '2003-08-01', '2006-08-01', 3, None],
       ['TAM', '2005-04-01', '2006-11-01', 1, None],
       ['US-CMW', '2001-04-01', '2019-10-01', 18, None],
       ['US-NC4', '2019-12-01', '2019-12-01', 0, None],
       ['US-Skr', '2004-02-01', '2011-05-01', 7, None],
       ['US-Sne', '2016-06-01', '2019-11-01', 3, None],
       ['US-Srr', '2014-04-01', '2017-09-01', 3, None],
       ['VR', '2003-03-01', '2004-05-01', 1, None]], dtype=object)

In [5]:
site_time[:,4].astype('F')
site_time[:,4] = 0
for i in range(len(site_time)):
  for j in range(len(openET)):
    if site_id[j] == site_time[i,0]:
      site_time[i,4] = site_time[i,4] + 1
columns = ('Site ID', 'Start Date', 'End Date', '# of Years', '# of Occurrences')
df = pd.DataFrame(data=site_time, columns = columns)

In [6]:
min_years = 10
long_sites = site_time[site_time[:,3] > min_years]
df = pd.DataFrame(data=long_sites, columns = columns)
print(df)

   Site ID  Start Date    End Date # of Years # of Occurrences
0   US-GLE  2001-06-01  2017-11-01         16              103
1   US-Me2  2002-03-01  2020-06-01         18              104
2   US-NR1  2001-02-01  2019-12-01         18              184
3   US-ARM  2003-01-01  2020-08-01         17               86
4   US-Ne1  2001-07-01  2019-12-01         18              203
5   US-Ne2  2001-07-01  2019-12-01         18              202
6   US-Ne3  2001-07-01  2019-12-01         18              197
7   US-SRG  2008-06-01  2020-05-01         11               78
8   US-Var  2003-11-01  2020-07-01         16              200
9   US-Wkg  2004-06-01  2020-05-01         15               48
10  US-MMS  2004-04-01  2020-06-01         16              111
11  US-WCr  2006-06-01  2019-06-01         12               12
12  US-SRM  2004-02-01  2020-05-01         16               96
13  US-CMW  2001-04-01  2019-10-01         18              121

In [9]:
site_year_counts = {}
years = range(2001, 2021)

for site in long_sites[:, 0]:
  site_year_counts[site] = {}
  for year in years:
    site_year_counts[site][year] = 0

for i in range(len(openET)):
  site = site_id[i]
  if site in long_sites[:, 0]:
    year = datetime.strptime(dates[i], '%Y-%m-%d').year
    if year in years:
      site_year_counts[site][year] += 1

df_year_counts = pd.DataFrame.from_dict(site_year_counts, orient='index', columns=years).fillna(0)
df_year_counts.to_latex("site_counts.txt")
df_year_counts

,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
US-GLE,1,0,0,3,7,9,9,7,6,8,7,9,7,8,7,8,7,0,0,0
US-Me2,0,8,0,2,3,2,1,2,5,4,5,6,8,5,9,10,10,10,8,6
US-NR1,10,12,10,12,9,11,7,8,8,9,7,11,8,8,11,9,12,12,10,0
US-ARM,0,0,5,4,5,12,4,5,5,6,8,9,2,7,3,2,3,2,1,3
US-Ne1,6,12,12,12,12,12,12,12,12,12,12,12,12,12,4,4,10,11,12,0
US-Ne2,6,12,12,12,12,12,12,12,12,12,12,12,12,12,5,3,10,10,12,0
US-Ne3,6,12,12,12,12,12,12,12,12,12,12,12,12,12,0,3,10,10,12,0
US-SRG,0,0,0,0,0,0,0,4,7,5,8,4,3,9,5,9,7,9,5,3
US-Var,0,0,2,12,12,12,12,12,12,11,12,12,12,12,12,12,12,12,12,7
US-Wkg,0,0,0,1,6,2,5,3,2,3,3,3,2,2,3,1,4,4,2,2
US-MMS,0,0,0,5,1,0,8,6,5,7,4,6,11,9,11,10,10,7,6,5
US-WCr,0,0,0,0,0,2,0,0,0,0,0,0,1,1,3,1,2,0,2,0
US-SRM,0,0,0,8,6,3,7,6,6,5,5,5,3,7,4,3,8,9,6,5
US-CMW,5,7,4,5,5,6,8,9,6,4,6,9,9,4,5,8,9,5,7,0